# Generated by Django 3.1.13 on 2021-09-28 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
